### ISSUE TITLE
Break-up the `DataLakeSasTest` to test individual components more granularly so that it is easier to debug and isolate failures

### ISSUE THREAD

**Issue by ahsonkhan** [Azure/azure-sdk-for-cpp#1096]
Follow unit-testing approach so that a test failure more easily indicates what the potential root causes of the failures are. If a larger, integration test is needed, it might be OK to keep this test, but it is better to have specific isolated tests.

https://github.com/Azure/azure-sdk-for-cpp/blob/24c0e726013d175fd6fca96b4f1bf87050aa63c9/sdk/storage/azure-storage-files-datalake/test/datalake_sas_test.cpp#L11-L18

For example, this test is failing in CI in https://github.com/Azure/azure-sdk-for-cpp/pull/897
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=645512&view=logs&j=85fce603-27e7-519e-7104-469f916f4b56&t=edb25b00-9fec-5e59-0001-6ccd95be0f23
```text
108: [ RUN      ] DataLakeFileSystemClientTest.DataLakeSasTest
108: D:\a\1\s\sdk\storage\azure-storage-files-datalake\test\datalake_sas_test.cpp(405): error: Expected: verify_file_read(sasToken) doesn't throw an exception.
108:   Actual: it throws.
108: [  FAILED  ] DataLakeFileSystemClientTest.DataLakeSasTest (10818 ms)
```

But the issue doesn't reproduce locally. Figuring out what state or service API call is the prime root cause is quite difficult, let alone understanding the goal of this test.

cc @katmsft, @Jinming-Hu

**Comment by ahsonkhan** [comment]
Looks like this test failure is intermittent.

**Comment by Jinming-Hu** [comment]
It hasn't failed in a long time. I think it's stable enough and the refactoring is not necessary for now.
